// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $api_survey_username_ from "./routes/api/survey/[username].ts";
import * as $index from "./routes/index.tsx";
import * as $survey_index from "./routes/survey/index.tsx";
import * as $Analysis from "./islands/Analysis.tsx";
import * as $Survey from "./islands/Survey.tsx";
import * as $SurveyConfirmation from "./islands/SurveyConfirmation.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/api/survey/[username].ts": $api_survey_username_,
    "./routes/index.tsx": $index,
    "./routes/survey/index.tsx": $survey_index,
  },
  islands: {
    "./islands/Analysis.tsx": $Analysis,
    "./islands/Survey.tsx": $Survey,
    "./islands/SurveyConfirmation.tsx": $SurveyConfirmation,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
